global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'my-nodejs-app'
    static_configs:
      - targets: ['0.0.0.0:80'] # Assuming your Node.js application is running on localhost:80
    metrics_path: '/' # The endpoint where your application exposes metrics
