name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      #- name: Run lint
      #  run: npm run lint
      #- name: Run tests
      #  run: npm test
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app-image .
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app-image:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]  # This job depends on the successful completion of the "build" job
    steps:
      - uses: actions/checkout@v3
      - name: Login to AWS EC2
        env:
            PRIVATE_KEY: ${{ secrets.EC2_PASSWORD }}
            HOSTNAME: ${{secrets.EC2_HOST}}
            USER_NAME: ${{secrets.EC2_USER}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            sudo yum update
            sudo yum install docker
            sudo systemctl enable docker
            sudo systemctl enable docker
            sudo docker stop my-app-iamge || true
            sudo docker rm my-app-image ||true
            sudo docker pull ${{secrets.DOCKER_USERNAME }}/my-app-image:latest
            sudo docker -d run my-app-iamge -p 3000:80 ${{secrets.DOCKER_USERNAME }}/my-app-image:latest
            '
